AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  expense-app

  SAM Template for expense-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  plaidClientId:
    Type: String
    Description: Plaid client Id
    Default: clientID
  plaidSecret:
    Type: String
    Description: Plaid secret
    Default: secret
  plaidUsername:
    Type: String
    Description: Username for plaid bank account
    Default: username
  plaidPassword:
    Type: String
    Description: password for plaid bank api
    Default: password
  twilioAccountSid:
    Type: String
    Description: Account SID of Twilio account
  twilioAuthToken:
    Type: String
    Description: Auth Token of Twilio account
  sendToNumber:
    Type: String
    Description: E164 formatted number to send messages to
  fromNumber:
    Type: String
    Description: E164 formatted Twilio number messages are sent from

Resources:
  # We could seperate out the modules here but for this use case
  # have decided to group them in a single layer
  ExpenseAppDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: expense-app-dependencies
      Description: dependencies required for the expense app lambda's
      ContentUri: lambdas/dist/dependencies
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs14.x
  CheckWeeksExpenseLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/dist/checkWeeksExpense
      Handler: checkWeeksExpense.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Layers:
        - !Ref ExpenseAppDependenciesLayer
      Environment:
        Variables:
          PLAID_CLIENT_ID: !Ref plaidClientId
          PLAID_SECRET: !Ref plaidSecret
          PLAID_USERNAME: !Ref plaidUsername
          PLAID_PASSWORD: !Ref plaidPassword
          ACCOUNT_SID: !Ref twilioAccountSid
          AUTH_TOKEN: !Ref twilioAuthToken
          SEND_TO: !Ref sendToNumber
          FROM_NUMBER: !Ref fromNumber
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ExpenseStore
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 ? * MON *) # 10AM every monday
  IvrCompleteLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/dist/ivrComplete
      Handler: ivrComplete.lambdaHandler
      Runtime: nodejs14.x
      Timeout: 15
      Architectures:
        - x86_64
      Layers:
        - !Ref ExpenseAppDependenciesLayer
      Environment:
        Variables:
          ACCOUNT_SID: !Ref twilioAccountSid
          AUTH_TOKEN: !Ref twilioAuthToken
          SEND_TO: !Ref sendToNumber
          FROM_NUMBER: !Ref fromNumber
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref ExpenseStore
      Events:
        IvrComplete:
          Type: Api
          Properties:
            Path: /ivrComplete
            Method: get
            RestApiId:
              Ref: TwilioApi
            RequestParameters:
              - method.request.querystring.target:
                  Required: true
                  Caching: false
  ExpenseStore:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: expenses-log
      KeySchema:
        - AttributeName: "year"
          KeyType: "HASH"
        - AttributeName: "week"
          KeyType: "RANGE"
      AttributeDefinitions:
        - AttributeName: "year"
          AttributeType: "N"
        - AttributeName: "week"
          AttributeType: "N"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  TwilioApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Twilio-Api
      StageName: v1
      Auth:
        ApiKeyRequired: true
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Join ["-", [TwilioApi, "ApiKey"]]
      Description: API key for calls from Twilio
      Enabled: true
      GenerateDistinctId: false
  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: TwilioApi
    Properties:
      ApiStages:
        - ApiId: !Ref TwilioApi
          Stage: v1
      Description: !Join ["-", [TwilioApi, "UsagePlan"]]
      UsagePlanName: !Join ["-", [TwilioApi, "UsagePlan"]]
  ApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan
