AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  expense-app

  SAM Template for expense-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  plaidClientId:
    Type: String
    Description: Plaid client Id
    Default: clientID
  plaidSecret:
    Type: String
    Description: Plaid secret
    Default: secret
  plaidUsername:
    Type: String
    Description: Username for plaid bank account
    Default: username
  plaidPassword:
    Type: String
    Description: password for plaid bank api
    Default: password

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/dist
      Handler: checkWeeksExpense.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          PLAID_CLIENT_ID: !Ref plaidClientId
          PLAID_SECRET: !Ref plaidSecret
          PLAID_USERNAME: !Ref plaidUsername
          PLAID_PASSWORD: !Ref plaidPassword
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 7 * * MON *) # 7AM every monday

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
